routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostsController;


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::middleware(['auth'])->group(function () {

    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('categories', 'CategoriesController');

    Route::resource('posts', 'PostsController');
    Route::resource('tags', 'TagsController');

    Route::get('trashed-posts', 'PostsController@trashed')->name('trashed-posts.index');

    Route::put('restore-posts/{post}', 'PostsController@restore')->name('restore-posts');
});

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $fillable = ['name'];
    //
}

app/Http/Controllers/TagsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Tags\CreateTagRequest;
use App\Http\Requests\Tags\UpdateTagRequest;
use App\Tag;
use Illuminate\Http\Request;

class TagsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('tags.index')->with('tags',Tag::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tags.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateTagRequest $request)
    {
        Tag::create([
            'name' => $request->name
        ]);
        session()->flash('success', 'Tag Created Successfully');
        return redirect(route('tags.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Tag $tag)
    {
        $tag->delete();
        session()->flash('success', 'Tag deleted Successfully');
        return redirect(route('categories.index'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {
        return view('categories.create')->with('tag',$tag);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateTagRequest $request, Tag $tag)
    {
            $tag->update([
                'name' => $request->name
            ]);
            session()->flash('success', 'Tag updated Successfully');
            return redirect(route('categories.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag)
    {

    }
}

resources/views/tags/create.blade.php
@extends('layouts.app')

@section('content')

<div class="card">
    <div class="card-header">
        {{ isset($tag) ? 'Edit Tag' : 'Create Tag'}}
    </div>
    <div class="card-body">
        @include('partials.errors')
        <form method="POST" action="{{  isset($tag) ? route('tags.update', $tag -> id) : route('tags.store')  }}">
            @csrf
            @if (  isset($tag))
            @method('PUT')
            @endif
            <div class="form-group">
                <label for="name">Name</label>
            <input id="name" class="form-control" value="{{ isset($tag) ? $tag -> name : '' }}" type="text" name="name">
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success"> {{ isset($tag) ? 'update Tag' : 'Add Tag'}}</button>
            </div>
        </form>
    </div>
</div>

@endsection

resources/views/tags/index.blade.php
@extends('layouts.app')

@section('content')
<div class="d-flex justify-content-end mb-2">
    <a href="{{ route('tags.create') }}" class="btn btn-success float-right">Add tag</a>
</div>
<div class="card">
    <div class="card-header">
        Tags
    </div>
    <div class="card-body">
        @if ($tags->count()>0)
        <table class="table">
            <thead>
                <th>Names</th>
                <th></th>
                <th></th>
            </thead>
            <tbody>
                @foreach ($tags as $tag)
                <tr>
                    <td>
                        {{ $tag -> name}}
                    </td>
                    <td>
                        <a href="{{ route('tags.edit', $tag->id)}}" class="btn btn-info btn-sm">Edit</a>
                    </td>
                    <td>
                        <a href="{{ route('tags.destroy', $tag->id)}}" class="btn btn-danger btn-sm">Delete</a>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        @else
        <h3 class="text-center">No Tags Yet</h3>
        @endif
    </div>
</div>

@endsection