routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostsController;


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::middleware(['auth'])->group(function () {

    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('categories', 'CategoriesController');

    Route::resource('posts', 'PostsController');
    Route::resource('tags', 'TagsController');

    Route::get('trashed-posts', 'PostsController@trashed')->name('trashed-posts.index');

    Route::put('restore-posts/{post}', 'PostsController@restore')->name('restore-posts');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Storage;

class Post extends Model
{
    use SoftDeletes;
    protected $fillable = ['title','description','content','image','published_at','category_id'];

    /**
     * Delete Image from storage
     *
     * @return void
     */
    public function deleteImage()
    {
        Storage::delete($this->image);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\Posts\CreatePostsRequest;
use App\Http\Requests\Posts\UpdatePostRequest;
use App\Post;


class PostsController extends Controller
{

        public function __construct()
        {
            $this->middleware('verifyCategoriesCount')->only(['create','store']);
        }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('posts.index')->with('posts', Post::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create')->with('categories',Category::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreatePostsRequest $request)
    {
        $image =  $request->image->store('posts');
        Post::create([
            'title' => $request->title,
            'description' => $request->description,
            'content' => $request->content,
            'published_at'=>$request->published_at,
            'image' => $image,
            'category_id' => $request->category
        ]);
        session()->flash('success', 'Post Created Successfully');
        return redirect(route('posts.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        return view('posts.create')->with('post',$post)->with('categories',Category::all());
    }

    /**
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePostRequest $request,Post $post)
    {

        $data = $request->only(['title','description','published_at','content','category']);
        if($request->hasFile('image'))
        {
            $image =$request->image->store('posts');
            $post->deleteImage();
            $data['image'] = $image;
        }

        $post->update($data);
        session()->flash('success', 'Post Updated Successfully');
        return redirect(route('posts.index'));
    }

    /**
     * Remove the specified resource from storage.
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::withTrashed()->where('id',$id)->firstOrFail();
        if ($post->trashed()) {
            $post->deleteImage();
            $post->forceDelete();
        } else {
            $post->delete();
        }
        session()->flash('success', 'Post Deleted Successfully');
        return redirect(route('posts.index'));
    }
    /**
     *
     * Display a list of trashed posts
     *
     * @return \Illuminate\Http\Response
     */
    public function trashed()
    {
        $trashed = Post::onlyTrashed()->get();

        return view('posts.index')->withPosts($trashed);
    }

    /**
     *
     * restore a trashed post
     * @return \Illuminate\Http\Response
     *
     *
     */
    public function restore($id)
    {
        $post = Post::withTrashed()->where('id',$id)->firstOrFail();
        $post->restore();
        session()->flash('success', 'Post Restored Successfully');
        return redirect()->back();
    }
}

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('content')

<div class="card">
    <div class="card-header">
        {{ isset($post) ? 'Edit Post' : 'Create post'}}
    </div>
    <div class="card-body">
        @include('partials.errors')
        <form method="POST" enctype="multipart/form-data"
            action="{{  isset($post) ? route('posts.update', $post -> id) : route('posts.store')  }}">
            @csrf
            @if ( isset($post))
            @method('PUT')
            @endif
            <div class="form-group">
                <label for="title">Title</label>
                <input id="title" class="form-control" value="{{ isset($post) ? $post -> title : '' }}" type="text"
                    name="title">
            </div>
            <div class="form-group">
                <label for="content">Description</label>
                <textarea name="description" id="description" class="form-control" cols="30"
                    rows="5">{{ isset($post) ? $post -> description : '' }}</textarea>
            </div>
            <div class="form-group">
                <label for="content">Content</label>
                <input id="content" type="hidden" name="content" value="{{ isset($post) ? $post -> content : '' }}">
                <trix-editor input="content"></trix-editor>
            </div>
            <div class="form-group">
                <label for="published_at">Published At</label>
                <input id="published_at" class="form-control" value="{{ isset($post) ? $post -> published_at : '' }}"  type="text" name="published_at">
            </div>
            @if (isset($post))
                <div class="form-group">
                    <img src="http://127.0.0.1:8000/storage/{{ $post -> image }}" style="width: 100%" alt="">
                </div>
            @endif
            <div class="form-group">
                <label for="image">Image</label>
                <input id="image" class="form-control" type="file" name="image">
            </div>
            <div class="form-group">
                <label for="category">Category</label>
                <select name="category" id="category" class="form-control">
                    @foreach ($categories as $category)
                <option value="{{ $category -> id}}"
                    @if (isset($post))
                    @if ( $category -> id == $post->category_id)
                    selected
                    @endif
                    @endif>{{ $category -> name}}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success"> {{ isset($post) ? 'update post' : 'Add post'}}</button>
            </div>
        </form>
    </div>
</div>

@endsection


@section('script')
<script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.js"></script>
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script>
        flatpickr('#published_at',{
            enableTime : true
        });
</script>
@endsection
@section('css')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')


@section('content')
<div class="d-flex justify-content-end mb-2">
    <a href="{{ route('posts.create') }}" class="btn btn-success float-right">Add Post</a>
</div>
<div class="card">
    <div class="card-header">
        Posts
    </div>
    <div class="card-body">
        @if ($posts->count()>0)
        <table class="table">
            <thead>
                <th>Image</th>
                <th>title</th>
                <th>Category</th>
                <th></th>
                <th></th>
            </thead>
            <tbody>
                @foreach ($posts as $post)
                <tr>
                    <td>
                        <img src="http://127.0.0.1:8000/storage/{{ $post -> image }}" width="100px" height="100px"
                            alt="">
                    </td>
                    <td>
                        {{ $post -> title}}
                    </td>
                    <td>
                        {{ $post -> category->name}}
                    </td>
                    @if (!$post->trashed() )
                    <td>
                        <a href="{{ route('posts.edit', $post->id)}}" class="btn btn-info btn-sm">Edit</a>
                    </td>
                    @else
                    <td>
                        <form method="POST" action="{{ route('restore-posts', $post->id)}}">
                            @csrf
                            @method('PUT')
                            <button type="submit" class="btn btn-info btn-sm">
                                Restore
                            </button>
                        </form>
                    </td>

                    @endif
                    <td>
                        <form method="POST" action="{{ route('posts.destroy', $post->id)}}">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger btn-sm">
                                {{ $post->trashed() ? 'Delete' : 'Trash' }}
                            </button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        @else
        <h3 class="text-center">No Posts Yet</h3>
        @endif
    </div>
    @endsection

</div>